#!/sbin/openrc-run

name=gotty

depend() {
    need net
    use logger
    need localmount
}

start() {
    ebegin "Starting gotty"
    start-stop-daemon --background --start --exec \
    /usr/bin/gotty \
    -u alpine \
    --make-pidfile --pidfile /run/gotty.pid \
    -- -w ssh alpine@localhost
    eend $?
}

stop() {
    ebegin "Stopping gotty"
    start-stop-daemon --stop --exec /usr/bin/gotty \
    --pidfile /run/gotty.pid \
    -s 1
    eend $?
}
